name: CI //after running 4

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          jave-version: 11
      - name: clean build
        run: ./gradlew clean test --info --stacktrace